services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: personal_blog_db
    ports:
      - "5432:5432"
  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgres://admin:secret@postgres:5432/personal_blog_db?sslmode=disable
    ports:
      - "8080:8080"
    depends_on:
      - postgres